<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ServiceNowLocation;
use App\TeamsCivic;

class Address extends Model
{

    //WHEREUAT_ADDRESS to SERVICENOWLOCATION field mappings
    public $addressMapping = [
        'street_number'             => 'houseNumber',
        'predirectional'            => 'preDirectional',
        'street_name'               => 'streetName',
        'street_suffix'             => 'streetSuffix',
        'postdirectional'           => 'postDirectional',
        'city'                      => 'city',
        'state'                     => 'state',
        'postal_code'               => 'postalCode',
        'country'                   => 'countryOrRegion',
        'latitude'                  => 'latitude',
        'longitude'                 => 'longitude',
    ];

    public function site()
    {
        return $this->hasOne('App\Site');
    }

    public function buildings()
    {
        return $this->hasMany('App\Building');
    }

    public function getTeamsCivic()
    {
        if(!$this->teams_civic_id)
        {
            return null;
        }
        return TeamsCivic::find($this->teams_civic_id);
    }

    public function getSite()
    {
        if($this->site)
        {
            return $this->site;
        }
        if($this->buildings->first())
        {
            return $this->buildings->first()->site;
        }
    }

    public function syncAdd()
    {
        print "Syncing ADDRESS...\n";
        if(!$this->teams_civic_id)
        {
            print "TEAMSCIVIC does not exist...  Creating!\n";
            $civic = $this->createTeamsCivic();
            if(!$civic)
            {
                $error = "Failed to create TEAMS CIVIC!\n";
                print $error;
                throw new Exception($error);
            }
            print "Created TEAMS CIVIC with ID {$civic->civicAddressId}...\n";
        } else {
            print "Found existing TEAMS CIVIC ID {$this->teams_civic_id}...\n";
            return $this->teams_civic_id;
        }
    }

    public function compareTeamsCivic($civic = null)
    {
        if(!$civic)
        {
            $civic = $this->getTeamsCivic();
        }

        $matches = true;
        foreach($this->addressMapping as $addressKey => $teamsKey)
        {
            if($addressKey == "country")
            {
                if($this->iso3166ToAlpha2($this->$addressKey) != $this->iso3166ToAlpha2($civic->$teamsKey))
                {
                    $matches = false;
                    break;
                }
            } else {
                if($this->$addressKey != $civic->$teamsKey)
                {
                    $matches = false;
                    break;
                }
            }
        }
        return $matches;
    }

    public function createTeamsCivic()
    {
        print "Address::createTeamsCivic()\n";
/*         $loc = $this->site->getServiceNowLocation();
        if(!$loc->hasValidFields())
        {
            print "SNOW LOC does not have valid fields!...\n";
            return null;
        } */
        $civic = new TeamsCivic;
        $civic->companyName = $this->getSite()->name;
        $civic->description = "Auto Generated by WHEREUAT system for site {$this->getSite()->name}.";
        foreach($this->addressMapping as $addressKey => $teamsKey)
        {
            $civic->$teamsKey = $this->$addressKey;
        }
        $civic->countryOrRegion = $this->iso3166ToAlpha2($this->country);

/*         $civic->houseNumber = $loc->u_street_number;
        $civic->houseNumberSuffix = $loc->u_street_suffix;
        $civic->preDirectional = $loc->u_street_predirectional;
        $civic->streetName = $loc->u_street_name;
        $civic->streetSuffix = $loc->u_street_suffix;
        $civic->postDirectional = $loc->u_street_postdirectional;
        $civic->city = $loc->city;
        $civic->state = $loc->state;
        $civic->postalCode = $loc->zip;
        $civic->countryOrRegion = static::iso3166ToAlpha2($loc->country);
        $civic->latitude = $loc->latitude;
        $civic->longitude = $loc->longitude; */
        $civicid = $civic->save();
        if(!$civicid)
        {
            $error = "Failed to create TEAMS CIVIC!\n";
            print $error;
            throw new Exception($error);
        }
        $civic->civicAddressId = $civicid;
        //$civic = TeamsCivic::find($civicid);
        $status = $civic->validate();
        if($status == false)
        {
            $error = "Failed to validate TEAMS CIVIC!\n";
            print $error;
            throw new Exception($error);
        }

        $this->teams_civic_id = $civic->civicAddressId;
        $this->save();
        return $civic;
    }

    public static function iso3166ToAlpha2($countrycode)
    {
        $codes = [
            'USA'   =>  'US',
            'US'    =>  'US',
            'CAN'   =>  'CA',
            'CA'    =>  'CA',
            'MEX'   =>  'MX',
            'MX'    =>  'MX',
        ];
        foreach($codes as $old => $new)
        {
            if(strtoupper($countrycode) == $old)
            {
                return $new;
            }
        }
    }

    public static function iso3166ToAlpha3($countrycode)
    {
        $codes = [
            'US'    =>  'USA',
            'USA'   =>  'USA',
            'CA'    =>  'CAN',
            'CAN'   =>  'CAN',
            'MX'    =>  'MEX',
            'MEX'   =>  'MEX',
        ];
        foreach($codes as $old => $new)
        {
            if(strtoupper($countrycode) == $new)
            {
                return $old;
            }
        }
    }

}
